version: 2.1

orbs:
  win: circleci/windows@2.2.0
  macos: circleci/macos@2.3.4

workflows:
  main:
    jobs:
        - Pip-PyPI
        - Pip-Local
        - Docker-Local
        - AWS
        #### UNIT TESTS
        - Linux:
            name: "Test | v3.8 | Linux"
            v: "3.8"
            mode: "TEST"
        - Linux:
            name: "Test | v3.9 | Linux"
            v: "3.9"
            mode: "TEST"
        - Linux:
            name: "Test | v3.10 | Linux"
            v: "3.10"
            mode: "TEST"
        # Ray does not work on 3.11
        # https://github.com/ray-project/ray/issues/33232
        # - Linux:
        #     name: "Test | v3.11 | Linux"
        #     v: "3.11"
        #     mode: "TEST"
        ### NOTEBOOKS
        - Linux:
            name: "Notebook | v3.8 | Linux"
            v: "3.8"
            mode: "NOTEBOOK"
        - Linux:
            name: "Notebook | v3.9 | Linux"
            v: "3.9"
            mode: "NOTEBOOK"
        - Linux:
            name: "Notebook | v3.10 | Linux"
            v: "3.10"
            mode: "NOTEBOOK"
        # - Linux:
        #     name: "Notebook | v3.11 | Linux"
        #     v: "3.11"
        #     mode: "NOTEBOOK"
        ### LINTER
        - Linux:
            name: "Linter | Linux"
            v: "3.10"
            mode: "LINTER"
        ### RAY
        - Linux:
            name: "Test | Ray | v3.10 | Linux"
            v: "3.10"
            mode: "RAY"
        - Windows:
            name: "Windows | v3.10"
        # test_create_index_doesn't work on MacOS
        # - MacOS:
        #    name: "MacOS | v3.10"
        # missing Torchvision
        #- Linux:
        #    name: "Linux -  v3.11"  
        #    v: "3.11"

jobs:
  Linux:
    parameters:
      v:
        type: string
        default: "3.10"
      mode:
        type: string
        default: "ALL"
    resource_class: large
    docker:
      # https://circleci.com/docs/circleci-images#language-image-variants
      - image: "cimg/python:<< parameters.v >>"
    steps:

      - checkout

      - restore_cache:
          keys:
            - v5-model_cache-{{ checksum "setup.py" }}
      
      - run:
          name: Install EVA package from GitHub repo with all dependencies
          command: |
            "python<< parameters.v >>" -m venv test_evadb
            pip install --upgrade pip
            source test_evadb/bin/activate
            pip install ".[dev]"

      # Enable Ray conditionally
      - when:
          condition: 
            equal: [ RAY, << parameters.mode >> ]
          steps:
            - run:
                name: Enable Ray setting in the config.yml file
                command: |
                  source test_evadb/bin/activate
                  python -c "import yaml;f = open('eva/eva.yml', 'r+');config_obj = yaml.load(f, Loader=yaml.FullLoader);config_obj['experimental']['ray'] = True;f.seek(0);f.write(yaml.dump(config_obj));f.truncate();"

      - run:
          name: Test and upload coverage report to coveralls
          no_output_timeout: 30m # 30 minute timeout
          command: |
            source test_evadb/bin/activate
            bash script/test/test.sh -m "<< parameters.mode >>"

      # Enable cache save conditionally (to avoid empty cache in Notebooks)
      - when:
          condition: 
            equal: [ TEST, << parameters.mode >> ]
          steps:
            - save_cache:
                key: v5-model_cache-{{ checksum "setup.py" }}
                paths:
                  - /home/circleci/.cache/huggingface/
                  - /home/circleci/.cache/torch/

  Windows:
      executor: win/default
      steps:
        - checkout
        - run: 
            name: Install EVA package from GitHub repo and run tests
            command: |
              choco install python --version=3.10.8 -y
              python --version
              pip --version
              pip install virtualenv
              virtualenv test_evadb
              test_evadb\Scripts\activate
              pip install ".[dev]"
              bash script\test\test.sh

  MacOS:
      macos:
        xcode: "14.2.0"
      steps:
        - run:           
            name: Setup Python
            command: |
              brew update
              brew install pyenv git
              pyenv install 3.10.8
              pyenv global 3.10.8
              eval "$(pyenv init -)"
              python --version
              pip --version
        - checkout
        - run:           
            name: Install EVA package from GitHub repo and run tests
            command: |
              python -m venv test_evadb
              source test_evadb/bin/activate
              pip install --upgrade pip
              pip debug --verbose
              pip install ".[dev]"
              source test_evadb/bin/activate
              bash script/test/test.sh 

  Pip-PyPI:
    resource_class: large
    docker:
      - image: "cimg/python:3.10"
    steps:
      - checkout
      - run:
          name: Install EVA package from PIP and start server
          command: |
            pip install --upgrade pip
            pip install evadb
            bash script/test/package.sh

  Pip-Local:
    resource_class: large
    docker:
      - image: "cimg/python:3.10"
    steps:
      - checkout
      - run:
          name: Install EVA package locally and start server
          command: |
            pip install --upgrade pip
            pip install "."
            bash script/test/package.sh

  Docker-Local:
    resource_class: large
    docker:
      - image: cimg/base:2023.05

    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build EVA Docker image and start server
          command: |
            docker build -t evadb docker
            timeout 30 docker run evadb || true

  AWS:
    resource_class: large
    docker:
      - image: cimg/aws:2023.05

    steps:
      - setup_remote_docker
      - run:
          name: Pull EVA Docker image and start server
          command: |
            aws --version
            docker pull evadbai/evaserver
            timeout 30 docker run evadbai/evaserver || true