name: 🐞 Bug Report
description: Problems with EvaDB
labels: [bug, triage]
body:

  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        🔍 Please search the [issues](https://github.com/georgia-tech-db/eva/issues) to see if a similar bug report already exists.
      options:
        - label: >
            I have searched the EvaDB [issues](https://github.com/georgia-tech-db/eva/issues) and found no similar bug report.
          required: true

  - type: textarea
    attributes:
      label: Bug
      description: 🖥️ Provide console output with error messages and/or screenshots of the bug.
      placeholder: |
        💡 ProTip! Include as much information as possible (screenshots, logs, tracebacks etc.) to receive the most helpful response.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment
      description: 🖥️ Please specify the software and hardware you used to produce the bug.
      placeholder: |
        - EvaDB: v2.0.1
        - OS: Ubuntu 20.04
        - Python: 3.9.0
        - GPU: Yes
        - Ray: Not installed
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Are you willing to submit a PR?
      description: >
        👍 (Optional) Please consider submitting a [Pull Request](https://github.com/georgia-tech-db/eva/pulls) (PR) to help improve EvaDB for everyone, especially if you have a good understanding of how to implement a fix or feature.
        Please see our ✅ [Contributing Guide](https://evadb.readthedocs.io/en/stable/source/contribute/index.html) to get started.
      options:
        - label: Yes I'd like to help by submitting a PR!
